# Generated by Django 4.2.7 on 2023-11-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fechaFinal',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fechaInicial',
            field=models.CharField(default='', max_length=8),
        ),
    ]
