# Generated by Django 4.2.7 on 2023-11-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_alter_prestamo_fechafinal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='cantidad',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='libro',
            name='cantidadPres',
            field=models.CharField(default=0, max_length=6),
        ),
    ]
